# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bf153018a65b0df2e668d64a82d961039f8cb3cca1d5c854a85ca6278498dd5d653d745676bd59e0a2050923eeaaee9d7ac8f839a4e1290c4e9e4fa573d23ec

test:
  secret_key_base: 2059b6f987ccc31029196bdf2ce024de6a30de4de0aa66aa3791f19f358159124ae591d7c233011644ee48a588b1cbb6b4aded9c6a0d8bca2390bb50f0cc31b5

production:
  secret_key_base: a0bb194a6eda270aa6dda8dcb7ffa9daaa1e23df098e9b65391f3502e09ccaeb012e4306603fb6e1a6d43df8eead9029158f8de413d4152faf9a33e80ce55929
